# Generated by Django 3.1.1 on 2020-09-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedMailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('date_of_deadline', models.DateField()),
                ('actual_date_on_which_reminder_is_to_be_sent', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('date_of_deadline', models.DateField()),
                ('actual_date_on_which_reminder_is_to_be_sent', models.DateField()),
                ('recurrence_type', models.IntegerField()),
                ('email_data', models.CharField(max_length=500)),
            ],
        ),
    ]
